In [260]:
import pandas as pd
import numpy as np
import function_ML
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA

In [261]:
data = pd.read_csv('weatherAUS.csv')
data=data.drop('RISK_MM',axis=1)

In [262]:
data.head(5)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,NaN,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [263]:
data.describe(include=['object'])

,Date,Location,WindGustDir,WindDir9am,WindDir3pm,RainToday,RainTomorrow
count,263,263,259,204,253,262,263
unique,263,1,16,16,16,2,2
top,2009-04-18,Albury,W,SSE,WNW,No,No
freq,1,263,47,29,31,208,208

In [264]:
data.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
count,259.000000,252.000000,262.000000,0.0,0.0,259.000000,261.000000,255.000000,255.000000,254.000000,255.000000,261.000000,99.000000,92.000000,263.000000,263.000000
mean,9.762934,23.132937,1.267939,NaN,NaN,34.023166,7.969349,14.258824,68.541176,43.066929,1017.187843,1014.429119,6.585859,5.836957,14.327376,21.897719
std,6.310679,8.697547,3.180129,NaN,NaN,15.363788,7.214237,7.726353,20.131587,22.802283,7.144678,7.001933,2.373365,2.734706,6.821129,8.507854
min,-2.000000,8.200000,0.000000,NaN,NaN,11.000000,0.000000,0.000000,20.000000,8.000000,994.300000,993.000000,0.000000,1.000000,1.900000,7.300000
25%,4.750000,15.450000,0.000000,NaN,NaN,22.000000,2.000000,9.000000,50.500000,23.000000,1011.650000,1009.000000,7.000000,4.000000,9.000000,14.500000
50%,9.100000,22.000000,0.000000,NaN,NaN,31.000000,6.000000,13.000000,71.000000,40.500000,1017.000000,1013.900000,8.000000,7.000000,13.600000,20.500000
75%,14.000000,30.400000,0.600000,NaN,NaN,43.000000,11.000000,19.000000,85.000000,61.000000,1022.750000,1019.700000,8.000000,8.000000,18.800000,29.100000
max,28.300000,44.800000,21.000000,NaN,NaN,98.000000,35.000000,48.000000,99.000000,97.000000,1034.100000,1029.900000,8.000000,8.000000,34.500000,43.400000

In [265]:
#unique location = 1 
data=data.drop('Location',axis=1)

In [266]:
data.isnull().sum()

Date               0
MinTemp            4
MaxTemp           11
Rainfall           1
Evaporation      263
Sunshine         263
WindGustDir        4
WindGustSpeed      4
WindDir9am        59
WindDir3pm        10
WindSpeed9am       2
WindSpeed3pm       8
Humidity9am        8
Humidity3pm        9
Pressure9am        8
Pressure3pm        2
Cloud9am         164
Cloud3pm         171
Temp9am            0
Temp3pm            0
RainToday          1
RainTomorrow       0
dtype: int64

In [267]:
# drop columns Evaporation,Sunshine,Cloud9am,Cloud3pm  
columns_names=['Evaporation','Sunshine','Cloud9am','Cloud3pm']
data=function_ML.drop_column(data,columns_names)

In [268]:
# replace value No and Yes 
data['RainToday']=data['RainToday'].replace('No',0)
data['RainToday']=data['RainToday'].replace('Yes',1)
data['RainTomorrow']=data['RainTomorrow'].replace('No',0)
data['RainTomorrow']=data['RainTomorrow'].replace('Yes',1)

In [269]:
data_num=['MinTemp','MaxTemp','Rainfall','WindGustSpeed','WindSpeed9am','WindSpeed3pm','Pressure9am', 
          'Pressure3pm','Humidity9am','Humidity3pm','Temp9am','Temp3pm','RainToday']
target=['RainTomorrow']
data_category=['WindGustDir','WindDir9am','WindDir3pm']

In [270]:
# Replacing nan with mode
for column_name in data_num:
    function_ML.replace_moda(data[column_name])

C:\Users\Ð¢Ñ‘Ð¼Ð°\function_ML.py:81: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  column[i]=mod

In [271]:
data.isnull().sum()

Date              0
MinTemp           0
MaxTemp           0
Rainfall          0
WindGustDir       4
WindGustSpeed     0
WindDir9am       59
WindDir3pm       10
WindSpeed9am      0
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Temp9am           0
Temp3pm           0
RainToday         0
RainTomorrow      0
dtype: int64

In [272]:
# Scaling 
for column_name in data_num:
    function_ML.scaling(data[column_name])

C:\Users\Ð¢Ñ‘Ð¼Ð°\function_ML.py:119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  column[i] = (column[i]-min_value)/(max_value-min_value)

In [273]:
# Create PCA with 3 components
pca = PCA(n_components=3)
pca.fit(data[data_num])
T = pca.transform(data[data_num])
T = pd.DataFrame(T)

In [274]:
# Split data to train/test sets
X_train, X_test, y_train, y_test = train_test_split(T, data[target], test_size=0.2, random_state=0)
# Create classifier
LR = LogisticRegression()
LR = LR.fit(X_train, y_train)
y_pred = LR.predict(X_test)
# Get accuracy score
accuracy_score(y_test, y_pred)

C:\programms\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\programms\Anaconda\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.7924528301886793

In [275]:
##############################################################
data = pd.read_csv('weatherAUS.csv')
data=data.drop('RISK_MM',axis=1)
data=data.drop('Location',axis=1) 
data=data.drop('Date',axis=1) 
columns_names=['Evaporation','Sunshine','Cloud9am','Cloud3pm']
data=function_ML.drop_column(data,columns_names)  
data['RainToday']=data['RainToday'].replace('No',0)
data['RainToday']=data['RainToday'].replace('Yes',1)
data['RainTomorrow']=data['RainTomorrow'].replace('No',0)
data['RainTomorrow']=data['RainTomorrow'].replace('Yes',1)

data_num=['MinTemp','MaxTemp','Rainfall','WindGustSpeed','WindSpeed9am','WindSpeed3pm','Pressure9am', 
          'Pressure3pm','Humidity9am','Humidity3pm','Temp9am','Temp3pm','RainToday']
target=['RainTomorrow']
data_category=['WindGustDir','WindDir9am','WindDir3pm']
data.isnull().sum()

MinTemp           4
MaxTemp          11
Rainfall          1
WindGustDir       4
WindGustSpeed     4
WindDir9am       59
WindDir3pm       10
WindSpeed9am      2
WindSpeed3pm      8
Humidity9am       8
Humidity3pm       9
Pressure9am       8
Pressure3pm       2
Temp9am           0
Temp3pm           0
RainToday         1
RainTomorrow      0
dtype: int64

In [276]:
data.corr()

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
MinTemp,1.000000,0.830242,0.013901,0.577379,0.389654,0.396418,-0.720177,-0.556745,-0.580751,-0.604198,0.947910,0.812242,-0.016895,-0.012533
MaxTemp,0.830242,1.000000,-0.249497,0.397138,0.106073,0.252870,-0.840483,-0.845274,-0.353789,-0.426460,0.922046,0.993200,-0.315929,-0.304346
Rainfall,0.013901,-0.249497,1.000000,0.254681,0.230673,0.138671,0.239355,0.361209,-0.286470,-0.225412,-0.107048,-0.258319,0.738819,0.314354
WindGustSpeed,0.577379,0.397138,0.254681,1.000000,0.545878,0.719889,-0.398352,-0.237925,-0.642980,-0.659649,0.526695,0.363623,0.153969,0.219008
WindSpeed9am,0.389654,0.106073,0.230673,0.545878,1.000000,0.532880,-0.304184,-0.052668,-0.554270,-0.473444,0.309614,0.075067,0.184764,0.157465
WindSpeed3pm,0.396418,0.252870,0.138671,0.719889,0.532880,1.000000,-0.312490,-0.212138,-0.547781,-0.521613,0.373031,0.241293,0.060734,0.071366
Humidity9am,-0.720177,-0.840483,0.239355,-0.398352,-0.304184,-0.312490,1.000000,0.830957,0.372889,0.397639,-0.843719,-0.831345,0.349912,0.288161
Humidity3pm,-0.556745,-0.845274,0.361209,-0.237925,-0.052668,-0.212138,0.830957,1.000000,0.132857,0.187134,-0.696790,-0.867540,0.455252,0.545563
Pressure9am,-0.580751,-0.353789,-0.286470,-0.642980,-0.554270,-0.547781,0.372889,0.132857,1.000000,0.969930,-0.512477,-0.310388,-0.194090,-0.193762
Pressure3pm,-0.604198,-0.426460,-0.225412,-0.659649,-0.473444,-0.521613,0.397639,0.187134,0.969930,1.000000,-0.560760,-0.390012,-0.109680,-0.195869
Temp9am,0.947910,0.922046,-0.107048,0.526695,0.309614,0.373031,-0.843719,-0.696790,-0.512477,-0.560760,1.000000,0.907105,-0.166285,-0.127036
Temp3pm,0.812242,0.993200,-0.258319,0.363623,0.075067,0.241293,-0.831345,-0.867540,-0.310388,-0.390012,0.907105,1.000000,-0.328207,-0.323671
RainToday,-0.016895,-0.315929,0.738819,0.153969,0.184764,0.060734,0.349912,0.455252,-0.194090,-0.109680,-0.166285,-0.328207,1.000000,0.316583
RainTomorrow,-0.012533,-0.304346,0.314354,0.219008,0.157465,0.071366,0.288161,0.545563,-0.193762,-0.195869,-0.127036,-0.323671,0.316583,1.000000

In [277]:
# predict values WindSpeed9am with linear regression (independ columns WindGustSpeed,WindSpeed3pm)
for column_name in ['WindGustSpeed','WindSpeed3pm']:
    function_ML.replace_mean(data[column_name])
function_ML.ln_regres(data,'WindSpeed9am',['WindGustSpeed','WindSpeed3pm'])

C:\Users\Ð¢Ñ‘Ð¼Ð°\function_ML.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  column[i]=mymean1
C:\programms\Anaconda\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
C:\programms\Anaconda\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,13.4,22.9,0.6,W,44.0,W,WNW,20.000000,24.000000,71.0,22.0,1007.7,1007.1,16.9,21.8,0.0,0
1,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.000000,22.000000,44.0,25.0,1010.6,1007.8,17.2,24.3,0.0,0
2,12.9,25.7,0.0,WSW,46.0,W,WSW,19.000000,26.000000,38.0,30.0,1007.6,1008.7,21.0,23.2,0.0,0
3,9.2,28.0,0.0,NE,24.0,SE,E,11.000000,9.000000,45.0,NaN,1017.6,1012.8,18.1,26.5,0.0,0
4,17.5,32.3,1.0,W,41.0,ENE,NW,7.000000,20.000000,82.0,33.0,1010.8,1006.0,17.8,29.7,0.0,0
5,14.6,29.7,0.2,NaN,56.0,W,W,19.000000,24.000000,55.0,23.0,1009.2,1005.4,20.6,28.9,0.0,0
6,14.3,25.0,0.0,W,50.0,SW,W,20.000000,24.000000,49.0,19.0,1009.6,1008.2,18.1,24.6,0.0,0
7,7.7,26.7,0.0,W,35.0,SSE,W,6.000000,17.000000,NaN,19.0,1013.4,1010.1,16.3,25.5,0.0,0
8,9.7,31.9,0.0,NNW,80.0,SE,NW,7.000000,28.000000,42.0,9.0,1008.9,1003.6,18.3,30.2,0.0,1
9,13.1,30.1,1.4,NaN,28.0,S,SSE,15.000000,11.000000,58.0,27.0,1007.0,1005.7,20.1,28.2,1.0,0
10,13.4,30.4,0.0,N,30.0,SSE,ESE,17.000000,6.000000,48.0,22.0,1011.8,1008.7,20.4,28.8,0.0,1
11,15.9,21.7,2.2,NNE,31.0,NE,ENE,15.000000,13.000000,89.0,91.0,1010.5,1004.2,15.9,17.0,1.0,1
12,15.9,18.6,15.6,W,61.0,NNW,NNW,28.000000,28.000000,76.0,93.0,994.3,993.0,17.4,15.8,1.0,1
13,12.6,21.0,3.6,SW,44.0,W,SSW,24.000000,20.000000,65.0,43.0,1001.2,1001.8,15.8,19.8,1.0,0
14,9.8,27.7,NaN,WNW,50.0,NaN,WNW,12.679145,22.000000,50.0,28.0,1013.4,1010.3,17.3,26.2,NaN,0
15,14.1,20.9,0.0,ENE,22.0,SSW,E,11.000000,9.000000,69.0,82.0,1012.2,1010.4,17.2,18.1,0.0,1
16,13.5,22.9,16.8,W,63.0,N,WNW,6.000000,20.000000,80.0,65.0,1005.8,1002.2,18.0,21.5,1.0,1
17,11.2,22.5,10.6,SSE,43.0,WSW,SW,24.000000,17.000000,47.0,32.0,1009.4,1009.7,15.5,21.0,1.0,0
18,9.8,25.6,0.0,SSE,26.0,SE,NNW,17.000000,6.000000,45.0,26.0,1019.2,1017.1,15.8,23.2,0.0,0
19,11.5,29.3,0.0,S,24.0,SE,SE,9.000000,9.000000,56.0,28.0,1019.3,1014.8,19.1,27.3,0.0,0
20,17.1,33.0,0.0,NE,43.0,NE,N,17.000000,22.000000,38.0,28.0,1013.6,1008.1,24.5,31.6,0.0,0
21,20.5,31.8,0.0,WNW,41.0,W,W,19.000000,20.000000,NaN,24.0,1007.8,1005.7,23.8,30.8,0.0,0
22,15.3,30.9,0.0,N,33.0,ESE,NW,6.000000,14.258824,55.0,23.0,1011.0,1008.2,20.9,29.0,0.0,0
23,12.6,32.4,0.0,W,43.0,E,W,4.000000,19.000000,49.0,17.0,1012.9,1010.1,21.5,31.2,0.0,0
24,16.2,33.9,0.0,WSW,35.0,SE,WSW,9.000000,13.000000,NaN,19.0,1010.9,1007.6,23.2,33.0,0.0,0
25,16.9,33.0,0.0,WSW,57.0,NaN,W,0.000000,26.000000,41.0,28.0,1006.8,1003.6,26.6,31.2,0.0,0
26,20.1,32.7,0.0,WNW,48.0,N,WNW,13.000000,30.000000,56.0,15.0,NaN,1001.7,24.6,32.1,0.0,0
27,19.7,27.2,0.0,WNW,46.0,NW,WSW,19.000000,30.000000,49.0,22.0,1004.8,1004.2,21.6,26.1,0.0,1
28,12.5,24.2,1.2,WNW,50.0,WSW,SW,11.000000,22.000000,78.0,70.0,1005.6,NaN,12.5,18.2,1.0,0
29,12.0,24.4,0.8,W,39.0,WNW,NaN,17.000000,17.000000,48.0,28.0,1006.1,1005.1,16.9,22.7,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,6.0,13.5,9.8,WNW,26.0,W,W,13.000000,17.000000,83.0,58.0,1015.1,1018.4,8.5,12.9,1.0,0
234,-0.1,12.9,0.0,NW,22.0,NaN,NNW,0.000000,15.000000,87.0,58.0,1027.3,1025.4,3.7,11.6,0.0,0
235,-0.3,12.2,0.0,NE,20.0,NaN,NE,0.000000,9.000000,95.0,61.0,1026.8,1022.7,2.5,10.8,0.0,0
236,2.1,9.8,0.0,SSE,13.0,NaN,E,0.000000,2.000000,85.0,74.0,1018.0,1013.7,4.4,9.6,0.0,0
237,1.3,8.8,0.0,N,20.0,ENE,NNW,6.000000,9.000000,99.0,91.0,1019.9,1019.9,4.2,7.3,0.0,1
238,4.2,12.7,3.8,WNW,31.0,NW,WNW,11.000000,11.000000,89.0,71.0,1024.0,1023.1,8.8,12.0,1.0,1
239,8.3,13.2,2.4,WNW,24.0,NW,WSW,11.000000,9.000000,98.0,81.0,1026.0,1025.4,9.3,12.1,1.0,0
240,3.3,12.1,0.2,NNW,22.0,NaN,WNW,0.000000,9.000000,99.0,76.0,1025.8,1022.7,6.5,12.0,0.0,1
241,6.5,14.5,5.2,W,35.0,W,WSW,19.000000,22.000000,81.0,61.0,1021.3,1021.5,11.6,12.7,1.0,0
242,7.4,13.9,0.2,W,30.0,NaN,WNW,0.000000,15.000000,99.0,70.0,1026.8,1025.3,8.9,13.3,0.0,0
243,7.5,14.1,0.8,NNW,30.0,SW,NNW,2.000000,17.000000,94.0,65.0,1027.9,1024.8,10.5,13.3,0.0,0
244,8.3,13.8,0.8,NNW,37.0,W,WNW,20.000000,15.000000,79.0,49.0,1023.1,1022.9,9.9,13.6,0.0,0
245,3.2,14.7,0.0,SSE,17.0,NaN,ENE,0.000000,4.000000,91.0,53.0,1021.7,1018.9,5.7,14.0,0.0,1
246,5.7,13.8,5.4,NNE,19.0,ENE,S,7.000000,7.000000,98.0,76.0,1022.2,1020.2,8.9,13.6,1.0,0
247,5.1,17.1,0.4,N,35.0,NaN,NE,0.000000,19.000000,99.0,58.0,1021.9,1016.7,8.0,16.6,0.0,0
248,8.0,13.9,0.8,WNW,57.0,WNW,WSW,35.000000,33.000000,79.0,47.0,1012.8,1015.6,9.8,13.7,0.0,1
249,-0.8,12.9,4.2,WNW,24.0,E,WSW,6.000000,6.000000,78.0,50.0,1026.4,1023.0,4.4,12.3,1.0,0
250,-1.0,12.2,0.0,ESE,15.0,S,E,2.000000,7.000000,91.0,48.0,1021.6,1018.5,2.0,12.1,0.0,0
251,1.9,14.8,0.2,SE,20.0,SSE,SE,4.000000,11.000000,72.0,60.0,1018.6,1014.7,5.9,12.6,0.0,0
252,5.9,17.7,0.4,NNE,43.0,E,NNW,19.000000,22.000000,62.0,59.0,1009.0,1008.6,14.8,15.6,0.0,1
253,6.9,14.3,4.8,W,24.0,SSE,NW,6.000000,13.000000,99.0,74.0,1011.5,1010.0,9.1,13.0,1.0,0
254,7.7,11.6,0.2,NW,22.0,NW,N,6.000000,13.000000,94.0,87.0,1015.7,1015.3,9.4,11.1,0.0,1
255,6.8,15.2,1.2,WSW,22.0,NaN,WNW,0.000000,13.000000,99.0,61.0,1021.1,1019.1,9.0,14.7,1.0,0
256,2.7,17.5,0.2,NNE,24.0,SE,NE,7.000000,13.000000,99.0,57.0,1021.2,1016.8,6.7,17.0,0.0,1
257,5.1,15.5,1.6,W,39.0,NE,ENE,11.000000,11.000000,79.0,70.0,1012.2,1006.4,11.0,14.3,1.0,1
258,4.2,13.6,3.2,WNW,37.0,W,WNW,20.000000,19.000000,73.0,57.0,1018.2,1019.7,9.8,12.8,1.0,0
259,0.6,15.6,0.0,WNW,15.0,NaN,S,0.000000,6.000000,85.0,58.0,1029.8,1027.2,6.0,14.4,0.0,0
260,1.6,16.4,0.0,E,17.0,NE,S,7.000000,7.000000,99.0,61.0,1027.7,1022.5,5.5,15.2,0.0,0
261,5.5,18.4,0.0,N,22.0,ESE,N,6.000000,13.000000,78.0,51.0,1019.7,1014.3,11.1,17.3,0.0,0
262,7.3,14.8,1.0,WNW,59.0,NNE,WSW,26.000000,30.000000,72.0,85.0,1004.0,1001.7,13.3,10.1,0.0,1

In [278]:
for column_name in data_num:
    function_ML.replace_mean(data[column_name])

C:\Users\Ð¢Ñ‘Ð¼Ð°\function_ML.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  column[i]=mymean1

In [279]:
# Convert categorical variables
for column_name in data_category:
    function_ML.replace_moda(data[column_name])
data=pd.get_dummies(data, columns=data_category) 
data_new=data.drop('RainTomorrow',axis=1)

C:\Users\Ð¢Ñ‘Ð¼Ð°\function_ML.py:81: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  column[i]=mod

In [280]:
data_new=data.drop('RainTomorrow',axis=1)
data_new.head(5)

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.000000,1007.7,1007.1,...,0,0,0,0,0,0,0,0,1,0
1,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.000000,1010.6,1007.8,...,0,0,0,0,0,0,0,0,0,1
2,12.9,25.7,0.0,46.0,19.0,26.0,38.0,30.000000,1007.6,1008.7,...,0,0,0,0,0,0,0,0,0,1
3,9.2,28.0,0.0,24.0,11.0,9.0,45.0,43.066929,1017.6,1012.8,...,0,0,0,0,0,0,0,0,0,0
4,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.000000,1010.8,1006.0,...,0,1,0,0,0,0,0,0,0,0

In [281]:
# Split data to train/test sets
X_train, X_test, y_train, y_test = train_test_split(data_new, data[target], test_size=0.2, random_state=0)
# Create classifier
LR = LogisticRegression()
LR = LR.fit(X_train, y_train)
y_pred = LR.predict(X_test)
accuracy_score(y_test, y_pred)

C:\programms\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\programms\Anaconda\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.8113207547169812

In [282]:
##############################################################
data = pd.read_csv('weatherAUS.csv')
data=data.drop('RISK_MM',axis=1)
data=data.drop('Location',axis=1) 
data=data.drop('Date',axis=1) 
columns_names=['Evaporation','Sunshine','Cloud9am','Cloud3pm']
data=function_ML.drop_column(data,columns_names)  
data['RainToday']=data['RainToday'].replace('No',0)
data['RainToday']=data['RainToday'].replace('Yes',1)
data['RainTomorrow']=data['RainTomorrow'].replace('No',0)
data['RainTomorrow']=data['RainTomorrow'].replace('Yes',1)

data_num=['MinTemp','MaxTemp','Rainfall','WindGustSpeed','WindSpeed9am','WindSpeed3pm','Pressure9am', 
          'Pressure3pm','Humidity9am','Humidity3pm','Temp9am','Temp3pm','RainToday']
target=['RainTomorrow']
data_category=['WindGustDir','WindDir9am','WindDir3pm']

In [283]:
for column_name in data_num:
    function_ML.replace_moda(data[column_name])

C:\Users\Ð¢Ñ‘Ð¼Ð°\function_ML.py:81: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  column[i]=mod

In [284]:
# Split data to train/test sets
X_train, X_test, y_train, y_test = train_test_split(data[data_num], data[target], test_size=0.2, random_state=0)
# Create classifier
LR = LogisticRegression()
LR = LR.fit(X_train, y_train)
y_pred = LR.predict(X_test)
accuracy_score(y_test, y_pred)

C:\programms\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\programms\Anaconda\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.8301886792452831